robotools/fontParts

- Lib/fontParts/objects/base/validators.py
Glyph name checking is per the UFO 3 spec, but do we want something more explicit in terms of the Adobe FDK rules?
Also, using the generic index check to do those checks, let me know if you want a more fine grained error.
> Some quick work on validators

- Lib/fontParts/objects/base/kerning.py
- Lib/fontParts/objects/base/validators.py
- Change signature of `BaseKerning.asDict(self)` to `BaseKerning.asDict(self, returnIntegers=True)` as in robofab (https://github.com/robofab-developers/robofab/blob/master/Lib/robofab/objects/objectsBase.py#L3404)
- Change validation of kern value to allow float (http://unifiedfontobject.org/versions/ufo3/kerning.plist/)
> Kern value as float

- Lib/fontParts/base/base.py
- documentation/source/environments/index.rst
- documentation/source/objects/anchor.rst
- documentation/source/objects/bpoint.rst
- documentation/source/objects/component.rst
- documentation/source/objects/contour.rst
- documentation/source/objects/font.rst
- documentation/source/objects/glyph.rst
- documentation/source/objects/groups.rst
- documentation/source/objects/guideline.rst
- documentation/source/objects/image.rst
- documentation/source/objects/info.rst
- documentation/source/objects/kerning.rst
- documentation/source/objects/layer.rst
- documentation/source/objects/lib.rst
- documentation/source/objects/point.rst
- documentation/source/objects/segment.rst
BaseDict has an update method to update the dictionary information. This will conflict with the generic update method, used (well, hopefully not) when an environment needs to be told to update an object. @typemytype noted that RoboFab used both "update" and "changed" to do this, and "changed" seems to be a better method name, so this branch switches the generic update to changed, leaving update as a method of BaseDict.
> Changed instead of Update

- documentation/source/conf.py
- documentation/source/environments/objects/normalizers.rst
- documentation/source/index.rst
- documentation/source/objects/anchor.rst
- documentation/source/objects/bpoint.rst
- documentation/source/objects/component.rst
- documentation/source/objects/contour.rst
- documentation/source/objects/features.rst
- documentation/source/objects/font.rst
- documentation/source/objects/glyph.rst
- documentation/source/objects/groups.rst
- documentation/source/objects/guideline.rst
- documentation/source/objects/image.rst
- documentation/source/objects/info.rst
- documentation/source/objects/kerning.rst
- documentation/source/objects/layer.rst
- documentation/source/objects/lib.rst
- documentation/source/objects/point.rst
- documentation/source/objects/segment.rst
Adding a quick reference to the top of doc pages, using the [autosummary](http://www.sphinx-doc.org/en/1.5.2/ext/autosummary.html) extension. Also adding missing object descriptions (copied from the robofab docs).
> [docs] adding autosummary extension, restructuring doc pages

- Lib/fontParts/base/contour.py
The expected behavior is that a contour's first segment's onCurve is the same point as the contour's second bPoint (that's a mouthful)
`_get_segments()` currently moves the first point of a closed contour to be the onCurve for the last segment when that last segment has offCurves (this is the correct behavior) but the points also need to be reordered if the last segment has no offCurves — the first point still needs to move to the end of the contour.
Sample glif file with two contours, one ends in a curve segment and one ends in a line segment:
```
<?xml version="1.0" encoding="UTF-8"?>
<glyph name="a" format="2">
<outline>
<contour>
<point x="140" y="50" type="curve"/>
<point x="140" y="124" type="line"/>
<point x="66" y="124" type="line"/>
<point x="66" y="83"/>
<point x="100" y="50"/> …
```
> Fixes segment order when a closed contour ends in a line segment

- Lib/fontParts/base/info.py
When making a ``.copy()`` of a font object, not all info attributes would be copied, with the old code the ``font.info.copyAttributes`` would be an empty tuple. I have to admit that I'm not certain if this change breaks any tests, but it seems to do the trick and matches how it looks in other objects.
Sample code:
```python
from fontParts.world import NewFont
from ufoLib import fontInfoAttributesVersion3
f = NewFont()
f.info.unitsPerEm = 200
f.info.postscriptFullName = "Test Font"
print(f.info.unitsPerEm) # 200
print(f.info.postscriptFullName) # "Test Font"
fCopy = f.copy()
print(fCopy.info.unitsPerEm) # None
print(fCopy.info.postscriptFullName) # None
```
> Fixes the copying of font info attributes

- Lib/fontParts/base/normalizers.py
Regarding issue #96 , kerning groups aren't required to start with an "@", and it looks like it's a valid character to start a group name with in the UFO3 spec, so I removed the condition that would raise an error.
> Removes the check for kerning group names in normalizeKerningKey()

- Lib/fontParts/base/image.py
This address #61 for py2 and py3. I didn't want to import the builtins object, as I don't have a firm grasp on what that would change in the object model between 2/3, so I did this. I don't know if it's super hacky/tacky or is just fine, so if you have a minute to review @anthrotype, I'd be greatly appreciative.
> Add __nonzero__ for py2 and __bool__ for py3 for RImage

- Lib/fontParts/base/font.py
- Lib/fontParts/base/layer.py
One thing I'm slightly unsure of is setting clear to `False` in font.py (https://github.com/robofab-developers/fontParts/compare/add-clear-to-glyph?expand=1#diff-b6f29e7842d51ccece52b2d48702e219R776). I'm following the comment that was existing there...
> Adding clear=True to newGlyph

- Lib/fontParts/base/glyph.py
fromMathGlyph will just replace the glyph object that calls the method with the mathGlyph, not exposing the private method's ability to not do this. This limit makes sense from what a scripter needs the functions for.
this is for #79
> Expose to/fromMathGlyph as a public functions. 

- Lib/fontParts/base/bPoint.py
- Lib/fontParts/base/base.py
- Lib/fontParts/base/font.py
- Lib/fontParts/base/glyph.py
- Lib/fontParts/base/segment.py
- Lib/fontParts/nonelab/base.py
- Lib/fontParts/test/test_anchor.py
- Lib/fontParts/test/test_bPoint.py
- Lib/fontParts/test/test_component.py
- Lib/fontParts/test/test_contour.py
- Lib/fontParts/test/test_features.py
- Lib/fontParts/test/test_font.py
- Lib/fontParts/test/test_glyph.py
- Lib/fontParts/test/test_groups.py
- Lib/fontParts/test/test_guideline.py
- Lib/fontParts/test/test_image.py
- Lib/fontParts/test/test_info.py
- Lib/fontParts/test/test_kerning.py
- Lib/fontParts/test/test_layer.py
- Lib/fontParts/test/test_point.py
- Lib/fontParts/test/test_segment.py
- documentation/source/environments/index.rst
* Add __hash__ and __eq__ from discustion in #52
* font doesn't seem to use BaseObject (it's pulled in via _BaseGlyphVendor)
* Add tests for all objects. Define hash for bPoint and segment. Add note that subclasses can override the default
* Remove the __eq__ from nonelab base.
* Adding __ne__ for Python 2, adding more tests, and separated the hash tests from the equality tests
* add __ne__ to environmental documentation, and a note that the base classes have these available as tests to the naked objects.
* If object can't compare, return `NotImpemented`. Improve the hash return of bPoint and segment to match values of equality testing. Move segment tests to a more logical spot in the file.
* Remove hash. Make __ne__ reflect Python 3 behavior (thank you @anthrotype) and state that …
> Adding __hash__ and __eq__ to objects (#118)

- Lib/fontParts/test/test_anchor.py
- Lib/fontParts/test/test_bPoint.py
- Lib/fontParts/test/test_component.py
- Lib/fontParts/test/test_contour.py
- Lib/fontParts/test/test_features.py
- Lib/fontParts/test/test_font.py
- Lib/fontParts/test/test_glyph.py
- Lib/fontParts/test/test_groups.py
- Lib/fontParts/test/test_guideline.py
- Lib/fontParts/test/test_image.py
- Lib/fontParts/test/test_info.py
- Lib/fontParts/test/test_kerning.py
- Lib/fontParts/test/test_layer.py
- Lib/fontParts/test/test_point.py
- Lib/fontParts/test/test_segment.py
Based on a conversation with @cjchapman, reworked tests to have one method per thing testing, also set the unrequested to a private variable that isn't passed to tests, as we *don't* want any of that tested.
> Refactor tests

- Lib/fontParts/base/contour.py
- Lib/fontParts/base/glyph.py
- Lib/fontParts/base/normalizers.py
- Lib/fontParts/fontshell/contour.py
- Lib/fontParts/fontshell/glyph.py
This addresses #146. It is dependent typesupply/defcon#174 on for the fontshell part to work.
> Implement base of glyph.correctDirection.

- Lib/fontParts/base/font.py
- Lib/fontParts/base/layer.py
The `duplicateLayer` method is absolutely necessary. I think the `swapLayerNames` method is necessary, but I could use an outside opinion. Even though swapping layers is simple in UI, doing this programmatically is unintuitive, so I figure that we should make this possible.
This addresses #178.
> Layer convenience methods.

- setup.py
One less file to bump when increasing the version.
Changes based on https://github.com/unified-font-object/ufoNormalizer/commit/7d595f46c84eb55621a8fa2ad6da155d9799804e
> Fetch the version number from __init__.py

- Lib/fontParts/base/deprecated.py
- Lib/fontParts/base/glyph.py
This restores the behavior as it [was in RoboFab](https://github.com/robofab-developers/robofab/blob/master/Lib/robofab/objects/objectsBase.py#L1463). This should close #148.
> Move isEmpty to deprecated.

- Lib/fontParts/base/contour.py
`contour.insertPoint()` needs the point index where the segment points should start to be inserted, but it's using the index given to `contour.insertSegment()` which was the segment index. The fix is to add up the total count of points up until the segment index.
> Fixes insertSegment so that the segment index isn't used as a point index

- setup.py
I noticed yesterday while doing a release of cu2qu (which also uses the custom `bump_version` and `release` setup.py commands) that, when running `setup.py release` without passing the `-s` option (the one that enables GPG signature for the git tag), then the resulting command-line that is passed on to the bumpversion script will contain an invalid `--sign-tags False` argument, and that produces a cryptic error, since the argument is wrongly interpreted by the bumpversion script as being one of the version "parts".
The fix is to completely omit boolean options that have a `False` value from the generated command line.
we should copy the same patch to all the rest of the projects that use these custom commands.
(yeah, I know. I should probably make a setuptools extension that one can …
> setup.py: fix issue with False boolean options in bump_version command

- Lib/fontParts/base/anchor.py
- Lib/fontParts/base/component.py
- Lib/fontParts/base/contour.py
- Lib/fontParts/base/guideline.py
- Lib/fontParts/base/image.py
- Lib/fontParts/base/layer.py
- Lib/fontParts/base/point.py
- Lib/fontParts/test/test_anchor.py
- Lib/fontParts/test/test_component.py
- Lib/fontParts/test/test_contour.py
- Lib/fontParts/test/test_guideline.py
- Lib/fontParts/test/test_image.py
- Lib/fontParts/test/test_layer.py
- Lib/fontParts/test/test_point.py
Related to #52 and #118, I think it's useful to have more objects be hashable. Ben had already added this functionality to the `font` and `glyph` objects so I followed the same pattern and added `__hash__` and its related tests to `anchor`, `component`, `contour`, `guideline`, `image`, `layer`, and `point` objects. 
The only two other objects that I didn't add this to, and that I think it could still be useful to have, are the `bPoint` and `segment` objects — I think I was running into problems because these are built dynamically.
> Adds hashability (and related tests) most remaining objects

- Lib/fontParts/base/bPoint.py
- Lib/fontParts/test/test_bPoint.py
I'd like to submit my tests for the bPoint object, with the understanding that many of them do fail in an expected way and will need to be reviewed. The problems are outlined in ticket #184 , where the bPoint object seems to lose track of its related point objects in some situations.
> Adds tests for the bPoint object

- Lib/fontParts/base/groups.py
subclasses may, not must, override private method
@typesupply, can you double check that this is correct?
> get_base_kerningGroup was redefined

- Lib/fontParts/base/glyph.py
- Lib/fontParts/test/test_deprecated.py
- Lib/fontParts/test/test_guideline.py
**Fixed**: Guideline tests to use getIdentifer, not deprecated generateIdentifier
**Fixed**: Glyph.lib needed to set it's parent like Font.lib
Finished Deprecated font test
Finished Deprecated guideline tests
> More Deprecated tests, WIP

- Lib/fontParts/base/deprecated.py
- Lib/fontParts/base/glyph.py
- Lib/fontParts/test/test_deprecated.py
- Lib/fontParts/test/test_glyph.py
This brings it back as a property, with the significant disadvantage that I don't see how to deprecate `isEmpty()` as a method (as `isEmpty` is now a bool, so...). As a property this feels right, as opposed to a method, but we can keep it as a method if that's easier.
> Bring isEmpty back

- Lib/fontParts/test/test_glyph.py
In tests that had `public.default` hard coded. This should use the default layer name from the environment.
> Use `defaultLayerName`

- documentation/source/objects/font.rst
If only the layer object is used, an error occurs.
```
TypeError: Layer names must be strings, not RLayer.
```
System used was Python 3.5.2 on Ubuntu Xenial 16.04 amd64
> Need the name of the layer

- Lib/fontParts/base/font.py
- Lib/fontParts/base/glyph.py
- Lib/fontParts/test/test_guideline.py
- NEWS.rst
Also, automatic whitespace fixes.
> Explicitly set parents when adding a guideline to glyph or font.

- Lib/fontParts/base/anchor.py
- Lib/fontParts/base/bPoint.py
- Lib/fontParts/base/component.py
- Lib/fontParts/base/contour.py
- Lib/fontParts/base/features.py
- Lib/fontParts/base/groups.py
- Lib/fontParts/base/guideline.py
- Lib/fontParts/base/image.py
- Lib/fontParts/base/info.py
- Lib/fontParts/base/kerning.py
- Lib/fontParts/base/layer.py
- Lib/fontParts/base/lib.py
- Lib/fontParts/base/point.py
- Lib/fontParts/base/segment.py
Removes asserts and replaces with a comparison check and a better detailed AssertionError message. Avoids ``assert`` being removed from complied byte code. Or so says Codacy.
> Remove asserts

- Lib/fontParts/test/test_guideline.py
A couple of missing tests. Down to the interpolation bits and the issue of how to set `None` in the object to get `None` back when the setter transforms `None` to 0. Load from an XML glyph? @typesupply any ideas?
> Mising guideline parent tests

- Lib/fontParts/test/test_groups.py
- Lib/fontParts/test/test_lib.py
(I think?) complete testing for groups.py, except for `_get_side1KerningGroups` and `_get_side2KerningGroups`, which are overridden in fontshell groups.py
> Groups testing

- Lib/fontParts/base/compatibility.py
- Lib/fontParts/base/glyph.py
- Lib/fontParts/test/test_glyph.py
Continuation of https://github.com/robofab-developers/fontParts/pull/368.
I made component mismatches a fatal error here, they were warnings before. I can imagine anchors not being strictly needed for interpolation, but components?
> Implement more precise component compatibility check

- Lib/fontParts/base/deprecated.py
- Lib/fontParts/test/test_deprecated.py
And made it a subclass from Exception. It's not a warning, it's only used as an exception to be raised when a deprecated method is called. It's a hard error.
> Renamed RemovedWarning to RemovedError

- README.rst
- dev-requirements.txt
Following the install instructions from the default [README.rst](https://github.com/robotools/fontParts/blob/master/README.rst) on the fontParts GitHub home page does not seem to actually work on Python 3 to get a working dev / testing environment. That leads to something like this:
```python
$ python Lib/fontParts/fontshell/test.py
Traceback (most recent call last):
File "Lib/fontParts/fontshell/test.py", line 1, in <module>
from fontParts.test import testEnvironment
File "/tmp/fontParts/Lib/fontParts/test/__init__.py", line 21, in <module>
from fontParts.test import test_deprecated
File "/tmp/fontParts/Lib/fontParts/test/test_deprecated.py", line 1, in <module>
import unittest2 as unittest
```
`unittest2` is not specified in the main `requirements.txt` file. TravisCI does not seem to …
> Slightly easier test / dev setup on Python 3

- documentation/source/objectref/objects/groups.rst
–updated examples for removing a glyph from a group. I converted to a list to use remove() then converted back to tuple. 
If there's a cleaner way to do this feel free to use that instead, but just thought I'd update this to a working example for now since I just hit this issue. Hope this helps!
> groups are tuples so remove() doesn't work

- Lib/fontParts/base/base.py
All incorrectly said `transformBy`
Fixes #514
> Update documentation for moveBy, scaleBy, rotateBy

- documentation/source/objectref/objects/groups.rst
I’ve tripped up a couple of times on the first example at https://fontparts.robotools.dev/en/stable/objectref/objects/groups.html, so here is a small edit that I think makes it accurate.
Was:
```
font = CurrentFont()
for name, members in font.groups.keys():
print name
print members
```
Should use `items()` instead:
```
font = CurrentFont()
for name, members in font.groups.items():
print name
print members
```
> Correct python typo in groups doc — was keys(), should be items()

- Lib/fontParts/base/glyph.py
- Lib/fontParts/base/info.py
- Lib/fontParts/base/kerning.py
- Lib/fontParts/test/test_glyph.py
- Lib/fontParts/test/test_info.py
- Lib/fontParts/test/test_kerning.py
Would fix #533  
This PR sets fontMath's `setRoundIntegerFunction` to use the `normalize.normalizeVisualRounding` function that the rest of fontParts uses for rounding, instead of the default Python3 `round` in the 4 places where fontMath rounding could take place.
I also added tests to make sure the rounding works as intended.
> Use normalizeVisualRounding for FontMath rounding

- Lib/fontParts/base/kerning.py
The docstring for kerning.get and kerning.find methods was the same, while they perform different operations. I hope this update clarifies the difference a bit.
> Clarify documentation for kerning.find

- Lib/fontParts/base/normalizers.py
Changed `"Kerning key items must be one character long"` to `"Kerning key items must be at least one character long"`.
Fixes #548
> Small edit to normalizeKerningKey error

- Lib/fontParts/__init__.py
Using implicit relative imports (`from _version import __version__`) does not work in recent python versions (tested with python 3.9.1).
Instead, using explicit path starting with `.` is the recommended way.
> Use explicit imports for _version

- Lib/fontParts/base/component.py
In the docs (https://fontparts.robotools.dev/en/stable/objectref/objects/component.html#attributes), this definition is slightly misleading. The method returns the glyph name for the referenced glyph – not the glyph object itself.
I think this small change will fix that.
> Make doc string more specific for baseComponent.baseGlyph

- Lib/fontParts/fontshell/glyph.py
I needed to be able to use this, it's part of the underlying `readGlyphFromString` API.
I also would not oppose letting `_loadFromGLIF` take `**kwargs` which it can pass down to `readGlyphFromString` at maintainer's (@benkiel's?) option, but I do need something like this please. :pleading_face:
> Add `validate` kwarg to `RGlyph._loadFromGLIF`

- Lib/fontParts/base/base.py
- Lib/fontParts/base/glyph.py
- Lib/fontParts/test/test_fuzzyNumber.py
- Lib/fontParts/test/test_glyph.py
- NEWS.rst
as #645 
This morning @typemytype realized that sorting `FuzzyNumber`s along with other types does not work as expected. So the old `roboFab` implementation needed some adjustments. I mark this as WIP as it might need some extra testing!
> Add implementation for `glyph.autoContourOrder()`

- documentation/source/objectref/objects/anchor.rst
- documentation/source/objectref/objects/features.rst
- documentation/source/objectref/objects/groups.rst
- documentation/source/objectref/objects/guideline.rst
- documentation/source/objectref/objects/point.rst
tabs seem to mess up layout on the web (the groups web page is the only one using spaces and it looks fine)
screenshots for reference:
+ anchors (using tabs)
+ groups (using spaces)
> update to print() + switch indentation to spaces

- Lib/fontParts/test/test_world.py
- Lib/fontParts/world.py
- documentation/source/objectref/fontpartsworld/index.rst
This addresses #545. I implemented it slightly differently than in the code I wrote for the issue. There is no need for the environment to define a function that only calls a standard function. Instead the environment registers its file extensions and those are used when no file extensions are given by the scripter.
> Implement OpenFonts.

- documentation/source/objectref/objects/info.rst
Fixes #689 
An attempt to add a link to the UFO specification in the description section of the Info object documentation... my first time messing with the docs, not sure if I did it right!
> Adding link to the UFO specification in the Info docs

- Lib/fontParts/test/test_glyph.py
This fixes the tests on Python 3.12, where assertEquals was removed.
> Replace remaining usage of assertEquals with assertEqual

- .gitignore
- Lib/fontParts/base/contour.py
- Lib/fontParts/base/font.py
- Lib/fontParts/base/glyph.py
- Lib/fontParts/base/normalizers.py
In cases where removed, the comprehensions were cast to a different type, where a generator expression is more efficient.
> Remove unecessary list comprehensions.

- .github/workflows/run-tests.yml
- Lib/fontParts/base/base.py
- Lib/fontParts/base/glyph.py
- Lib/fontParts/base/layer.py
Fixing test errors (now that I have `v1` being tested)
> Fix some annotation errors

- .gitignore
- Lib/fontParts/base/anchor.py
- Lib/fontParts/base/bPoint.py
- Lib/fontParts/base/base.py
- Lib/fontParts/base/compatibility.py
- Lib/fontParts/base/component.py
- Lib/fontParts/base/contour.py
- Lib/fontParts/base/deprecated.py
- Lib/fontParts/base/font.py
- Lib/fontParts/base/glyph.py
- Lib/fontParts/base/guideline.py
- Lib/fontParts/base/image.py
- Lib/fontParts/base/info.py
- Lib/fontParts/base/kerning.py
- Lib/fontParts/base/layer.py
- Lib/fontParts/base/normalizers.py
- Lib/fontParts/base/point.py
- Lib/fontParts/base/segment.py
- Lib/fontParts/test/test_component.py
- Lib/fontParts/test/test_contour.py
- Lib/fontParts/test/test_deprecated.py
- Lib/fontParts/test/test_font.py
- Lib/fontParts/test/test_glyph.py
- Lib/fontParts/test/test_world.py
- Lib/fontParts/world.py
- documentation/source/conf.py
Convert all formatting to strings
> fstring with flint

- Lib/fontParts/base/color.py
- Addresses `mypy` error concerning `*args`. 
- Deletes unnecessary tuple casting.
- Deletes unnecessary imports.
> Improve `Color`

- Lib/fontParts/base/contour.py
- Lib/fontParts/base/info.py
This takes care of a view errors thrown by fontshell modules.
> Resolve more `mypy` errors.

- Lib/fontParts/base/kerning.py
Warning example: `.venv/lib/python3.13/site-packages/fontParts/base/kerning.py:433: SyntaxWarning: invalid escape sequence '\s'`
> Mark `base.kerning.py` docstrings as raw to avoid `SyntaxWarning`

- Lib/fontParts/base/font.py
Annotating `fortshell` revealed a bug in copyData.
Tests of `copy` and `copyData` should probably make sure that source and target are not the same object, so that things like this gets caught.
> Fix bug in `BaseFont.copyData`.

- Lib/fontParts/base/annotations.py
- documentation/source/conf.py
- documentation/source/objectref/valuetypes/index.rst
`BaseLib` allows nested collection types (`list`, `tuple` and `dict`. Because of this, the type alias `LibValueType` has to use forward references as strings:
```python
LibValueType = Union[
str,
IntFloatType,
bool,
CollectionType["LibValueType"],
Dict[str, "LibValueType"],
bytes,
bytearray,
datetime.datetime,
]
```
Sphinx, in turn, will not resolve correctly in the generated documentation. 
- Add a `LibValue` class to `base.annotations` purely for the purpose of documenting these types.
- Replace the type alias with a reference to this class via `autodoc_type_aliases` in `conf.py`
- Generate documentation for the `LibValue` class in `objectref/valuetypes/index.rst`.
`BaseLibValue` might be a more appropriate name for this class.
> Document and resolve `LibValueType`
