Lib/fontParts/objects/base/validators.py
Is the duplicate checking too heavy handed/magical?
=> Validate layer order. 

Lib/fontParts/objects/base/validators.py
Two questions on this:
Is this how you want to check the angle being between 0 and 360?
I didn't see any use of validateGuideline in the rest of the code, so I just took a naïve stab at it; is this how things should work in these general purpose validators?
=> Validate guidelines.

documentation/source/objects/bpoint.rst, documentation/source/objects/glyph.rst, documentation/source/objects/image.rst
based on existing fontParts documentation for Font, and the old RoboFab documentation.
please review to make sure all is correct.
thanks!
=> Filling out gaps in documentation

Lib/fontParts/world.py
=> adding Glyph

.gitignore, Lib/fontParts/base/anchor.py, Lib/fontParts/base/bPoint.py, Lib/fontParts/base/component.py, Lib/fontParts/base/contour.py, Lib/fontParts/base/deprecated.py, Lib/fontParts/base/features.py, Lib/fontParts/base/font.py, Lib/fontParts/base/glyph.py, Lib/fontParts/base/groups.py, Lib/fontParts/base/guideline.py, Lib/fontParts/base/info.py, Lib/fontParts/base/kerning.py, Lib/fontParts/base/lib.py, Lib/fontParts/base/point.py, Lib/fontParts/base/segment.py, Lib/fontParts/test/test_anchor.py
This raises an exception for things that were in RoboFab but are not carried over. For #107
=> Add a Removed warning to deprecated

Lib/fontParts/base/anchor.py, Lib/fontParts/base/bPoint.py, Lib/fontParts/base/base.py, Lib/fontParts/base/component.py, Lib/fontParts/base/contour.py, Lib/fontParts/base/features.py, Lib/fontParts/base/glyph.py, Lib/fontParts/base/groups.py, Lib/fontParts/base/guideline.py, Lib/fontParts/base/image.py, Lib/fontParts/base/info.py, Lib/fontParts/base/kerning.py, Lib/fontParts/base/layer.py, Lib/fontParts/base/lib.py, Lib/fontParts/base/normalizers.py, Lib/fontParts/base/point.py, Lib/fontParts/base/segment.py
see https://github.com/robofab-developers/fontParts/issues/71#issuecomment-362708807
=> Remove weakref

Lib/fontParts/fontshell/test.py, Lib/fontParts/test/test_glyph.py
To reflect the name change from NoneLab to FontShell done in #144
=> Update name of test objects

Lib/fontParts/base/kerning.py, Lib/fontParts/fontshell/kerning.py, Lib/fontParts/test/test_kerning.py
This addresses #171. This can't be merged until typesupply/defcon/issues/4 is completed (the PR has been submitted).
=> Implement find method in kerning object.

Lib/fontParts/base/guideline.py, Lib/fontParts/test/test_guideline.py
This contains a handful of commented out tests. See #176 for the reason.
=> Guideline test cases.

Lib/fontParts/base/component.py, Lib/fontParts/base/contour.py, Lib/fontParts/base/normalizers.py, Lib/fontParts/test/test_component.py
Writing these revealed a few small bugs. Otherwise, this is pretty straightforward.
=> Component test cases.

Lib/fontParts/base/font.py, Lib/fontParts/base/layer.py, Lib/fontParts/base/normalizers.py, Lib/fontParts/fontshell/font.py, Lib/fontParts/test/test_font.py
=> Change "defaultLayer" to "defaultLayerName" and add new "defaultLayer" attribute that returns a layer.

Lib/fontParts/base/anchor.py, Lib/fontParts/base/bPoint.py, Lib/fontParts/base/base.py, Lib/fontParts/base/component.py, Lib/fontParts/base/contour.py, Lib/fontParts/base/font.py, Lib/fontParts/base/glyph.py, Lib/fontParts/base/guideline.py, Lib/fontParts/base/image.py, Lib/fontParts/base/info.py, Lib/fontParts/base/kerning.py, Lib/fontParts/base/layer.py, Lib/fontParts/base/point.py, Lib/fontParts/base/segment.py
=> Move identifier code to a mixin to reduce code duplication.

Lib/fontParts/base/base.py
=> support for dynamic getter for uninitiated object

Lib/fontParts/base/component.py, Lib/fontParts/fontshell/component.py, Lib/fontParts/test/legacyPointPen.py, Lib/fontParts/test/test_component.py
This should close #185. This tests everything except isCompatible.
=> More component tests.

Lib/fontParts/fontshell/glyph.py, Lib/fontParts/test/test_anchor.py
All tests for Anchor except for ``isCompatible``
=> Anchor tests

Lib/fontParts/base/normalizers.py, Lib/fontParts/base/segment.py, Lib/fontParts/test/__init__.py, Lib/fontParts/test/test_glyph.py, Lib/fontParts/test/test_groups.py, Lib/fontParts/test/test_normalizers.py
coverage reports this as `100%`.
=> Normalizer tests.

Lib/fontParts/test/test_anchor.py, Lib/fontParts/test/test_guideline.py
=> Use assertAlmostEqual

Lib/fontParts/base/groups.py, Lib/fontParts/base/kerning.py, Lib/fontParts/fontshell/groups.py, Lib/fontParts/test/test_groups.py
This should close #182. (Until we have `interpolate` and `isCompatibile` tests. :)
=> Kerning group interpolation

Lib/fontParts/base/base.py, Lib/fontParts/base/font.py, Lib/fontParts/base/glyph.py, Lib/fontParts/base/guideline.py, Lib/fontParts/base/normalizers.py, Lib/fontParts/test/test_normalizers.py
=> Consolidate normalizers

Lib/fontParts/fontshell/font.py
This seems like a premature optimization and, even if it's not, it's a
clumsy way to handle caching. It was never finished anyway. This
addresses #49.
=> Remove object caching.

Lib/fontParts/base/glyph.py
=> Don't use drawPoints in copyData and appendGlyph.

Lib/fontParts/fontshell/contour.py, Lib/fontParts/fontshell/glyph.py, Lib/fontParts/fontshell/point.py
See #157 and typesupply/defcon/issues/182. This closes #157.
=> Send point notifications.

Lib/fontParts/test/test_point.py
Finished off tests for the Point object. Some tests are failing, so there are either problems with the Point object or I may have misunderstood a few things from the examples that I saw. I would be very happy to make another pull request after fixing things, if this is the case.
I'll leave my questions in the related issue #196
=> Added tests for the point object (with questions)

.coveragerc
Artificially inflating the coverage numbers, and is just silly.
=> Remove tests from coverage.

.coveragerc, Lib/fontParts/base/contour.py, Lib/fontParts/base/deprecated.py, Lib/fontParts/base/layer.py, Lib/fontParts/test/__init__.py, Lib/fontParts/test/test_anchor.py, Lib/fontParts/test/test_deprecated.py, tox.ini
WIP, but fixes deprecated in Layer
=> Test deprecated

Lib/fontParts/base/guideline.py, Lib/fontParts/test/test_guideline.py
=> Fix angle calculation in guideline.transformBy()

documentation/source/environments/index.rst
This addresses and should hopefully close #20.
=> How to for environment specific additions.

Lib/fontParts/base/font.py
=> Add support for environment options in the generate method.

Lib/fontParts/base/contour.py
=> Add a preserve curve argument to removePoint and removeSegment.

Lib/fontParts/base/bPoint.py, Lib/fontParts/fontshell/contour.py, Lib/fontParts/test/test_bPoint.py
Failing tests are mostly about copy, which is up for debate. Will uncomment failing tests in this branch once merged, as this fixes some other issues.
=> Some bPoint test fixes

Lib/fontParts/test/__init__.py, Lib/fontParts/test/test_color.py
This is a bit silly, but it tests the Color attributes.
=> Tests for Color

Lib/fontParts/base/deprecated.py, Lib/fontParts/fontshell/contour.py, Lib/fontParts/test/test_deprecated.py
=> Deprecated tests

Lib/fontParts/base/contour.py, Lib/fontParts/base/font.py, Lib/fontParts/base/glyph.py, Lib/fontParts/base/layer.py, Lib/fontParts/fontshell/component.py, Lib/fontParts/fontshell/font.py, Lib/fontParts/fontshell/glyph.py, Lib/fontParts/test/test_font.py, Lib/fontParts/test/test_glyph.py, NEWS.rst
Also added a change log. This should close:
- #286
- #296
- #301
=> Improve list and dict like methods.

Lib/fontParts/base/font.py
instead of inserting other doc string in method
=> use sphinx attr reference

Lib/fontParts/base/base.py, Lib/fontParts/test/test_groups.py, Lib/fontParts/test/test_kerning.py
=> Fixes and tests for #324

Lib/fontParts/base/contour.py, Lib/fontParts/test/test_contour.py
See https://github.com/robofab-developers/fontParts/issues/334.
=> Contour.segments: Fix crash when off-curves at beginning and ending

Lib/fontParts/base/info.py
=> Add public functions to mathInfo

documentation/source/index.rst
=> Correct small spelling error

Lib/fontParts/base/font.py
=> Remove ().

Lib/fontParts/fontshell/image.py, Lib/fontParts/test/test_image.py, Lib/fontParts/test/test_normalizers.py
Fix PNGValidation in fontshell
Add a couple of more rounding tests in Normalizer
Closes #191
=> Test all of Image

.appveyor.yml, .travis.yml, .travis/install.sh, tox.ini
=> Cleanup Travis testing

Lib/fontParts/base/compatibility.py
Further cleanup based on @madig's work.
=> Remove redundant checks

Lib/fontParts/base/component.py, Lib/fontParts/base/contour.py, Lib/fontParts/base/info.py, Lib/fontParts/base/kerning.py, Lib/fontParts/fontshell/glyph.py, Lib/fontParts/fontshell/image.py, requirements.txt, setup.py
Remove ufoLib from requirements
Update minimum requirements in setup.py to get the right versions
Addresses https://github.com/robofab-developers/fontParts/pull/378#issuecomment-435017162
=> Change import of ufoLib to fontTools.ufoLib

Lib/fontParts/base/contour.py
excuses, the master branch is protected..
=> reuse the same BPoints list instead of requesting it again

Lib/fontParts/base/contour.py, Lib/fontParts/base/layer.py, Lib/fontParts/test/test_layer.py
@frankrolf could you test this PR before merging
thanks!!
=> Start segment+insert glyph

Lib/fontParts/base/font.py, Lib/fontParts/base/layer.py, Lib/fontParts/test/test_font.py
=> on font.insert try to preserve the gyph order

Lib/fontParts/test/test_world.py, Lib/fontParts/world.py
=> Fix arguement for OpenFont. Add a test.

Lib/fontParts/base/font.py
it will be the first layer from the layerOrder
fixes #419
=> set the required default layer

documentation/source/objectref/objects/font.rst
=> adding RFont.insertLayer to the docs

Lib/fontParts/base/font.py, Lib/fontParts/base/normalizers.py, Lib/fontParts/fontshell/font.py, Lib/fontParts/test/test_font.py
dont merg it yet, test are coming!!
=> adding support for fileStructure

Lib/fontParts/base/glyph.py, Lib/fontParts/fontshell/glyph.py, requirements.txt
Needs tests, can someone more familiar with removeOverlap (@miguelsousa, @typemytype?) take a look?
=> Fixes #405 and adds removeOverlap to fontShell

Lib/fontParts/base/anchor.py, Lib/fontParts/base/bPoint.py, Lib/fontParts/base/component.py, Lib/fontParts/base/glyph.py, Lib/fontParts/base/guideline.py, Lib/fontParts/base/image.py, Lib/fontParts/base/kerning.py, Lib/fontParts/base/normalizers.py, Lib/fontParts/base/point.py, Lib/fontParts/test/test_anchor.py, Lib/fontParts/test/test_guideline.py, Lib/fontParts/test/test_normalizers.py
Apply to all things visual. Fixes #454
=> Add a normalizer for visual rounding

Lib/fontParts/world.py
=> Undefined name: valueGetter —> valueName

Lib/fontParts/base/glyph.py, Lib/fontParts/fontshell/glyph.py, Lib/fontParts/test/test_glyph.py
=> Change how `glyph.unicode` behaves

Lib/fontParts/fontshell/font.py
Change if/elif/else order to test for `None` first
=> Accept a pathLikeObject, pass string to Defcon

Lib/fontParts/base/glyph.py, Lib/fontParts/test/test_glyph.py
=> Use copy in _appendContour only if there’s an offset

Lib/fontParts/base/contour.py, Lib/fontParts/test/test_contour.py
=> contour.segment can be empty

Lib/fontParts/fontshell/image.py
the data is a png anyway, so make it easier for fe git clients to recognise the data
=> add .png extension while making an image file name

Lib/fontParts/base/component.py
=> Fix PointPositionMixin error in component

requirements.txt, setup.py
BooleanOperations was added to give fontShell removeOverlap. Was added to requirements.txt, didn't get added to setup.py.
=> Correct setup.py

Lib/fontParts/fontshell/point.py
This seems to fix #546 and #549, but I have no idea how to test this.
=> set .dirty on naked(), not self; likely fixes #546 and #549

Lib/fontParts/test/test_glyph.py
Simple test for glyph `moveBy`
=> Test glyph move by

documentation/source/objectref/objects/info.rst
=> Correct info on font.info data checking

Lib/fontParts/base/contour.py, Lib/fontParts/test/test_contour.py
=> Fix contour insert segment

Lib/fontParts/base/font.py
Minor edit to match previously mixed up descriptions.
=> fix doc strings for getCharacterMapping and getReverseComponentMapping

Lib/fontParts/base/font.py, Lib/fontParts/test/test_font.py
=> force change the default layer name to the source defaultLayerName

Lib/fontParts/base/contour.py, Lib/fontParts/test/test_contour.py
=> add contour.setStartPoint + test

documentation/source/environments/objects/normalizers.rst, documentation/source/objectref/objects/point.rst
add .. autoclass:: BasePoint to Reference section.
=>  Update point.rst

Lib/fontParts/base/info.py, Lib/fontParts/test/test_font.py
=> Extract guidelines from math info

Lib/fontParts/base/base.py
See https://github.com/robotools/fontParts/pull/745#issuecomment-2391489355
=> Update base.reference doc

documentation/tools/docstring.py
- Corrected docstring indent error.
- Corrected line length.
=> Improve `docstring.py`.

Lib/fontParts/base/normalizers.py
=> Fix Python SyntaxWarning
